services:

  app:
    image: eclipse-temurin:17-jdk-alpine
    container_name: app-transfers
    volumes:
      - ./target/transfers-1.0.0-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    command: ["java", "-jar", "app.jar"]
    ports:
      - "8080:8080"
    depends_on:
      - db
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://db:1433;databaseName=bankFam;encrypt=true;trustServerCertificate=true
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: transferBank2019
      SPRING_RABBITMQ_HOST: rabbitmq
    networks:
      - app-network

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: transferBank-db
    hostname: sql1
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: transferBank2019
    ports:
      - "1433:1433"
    networks:
      - app-network

  rabbitmq:
    image: cyrilix/rabbitmq-mqtt
    container_name: rabbitmq_test
    ports:
      - "1883:1883"
      - "5672:5672"
      - "5671:5671"
      - "15672:15672"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
